services:
  web:
    build: .
    ports:
      - "30000:8080"
    environment:
      - VITE_INSTA_ACCESS=IGQWROOXNONmE1RVFDdUlfQUFKb2s1NnJOOWhRcUVMdXYzeGF4Q0JKeEhWVHpQd1lXUlVXOGxrbDBsMEpSdlpxVWFBdmtMbVdmX0hsWkxLSk1hTE5VbkdVUWY2TXk2ZAXpTc1FpTnVjTWJOYllsczAwOXNSV1Jpa0UZD
      - NGINX_PROTOCOL=
    volumes:
      - ./nginx-config/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx-config/templates:/etc/nginx/templates
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
