services:
  web:
    container_name: portfolio-web
    build: .
    ports:
      - "30000:8080"
    restart: unless-stopped
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/nginxconfig.io:/etc/nginx/nginxconfig.io:ro
      - ./nginx-config/templates:/etc/nginx/templates:ro
      - ./dist:/usr/share/nginx/html:ro
