services:
  web:
    build: .
    ports:
      - "30000:8080"
    environment:
      - NGINX_PROTOCOL=
    volumes:
      - /docker/portfolio/nginx-config/nginxconfig.io:/etc/nginx/nginxconfig.io
      - /docker/portfolio/nginx-config/templates:/etc/nginx/templates
      - /docker/portfolio/nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - /docker/portfolio/dist:/usr/share/nginx/html
